import type { MigrationInterface, QueryRunner } from "typeorm";

// Generated by TypeORM migration:generate on an empty PostgreSQL database.
// Reviewed additions: expression and INCLUDE/DESC indexes from HW-12.

export class InitialMarketplace1789797879157 implements MigrationInterface {
    name = 'InitialMarketplace1789797879157'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "orders" ("id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL, "user_id" bigint NOT NULL, "status" text NOT NULL DEFAULT 'pending', "total_cents" bigint NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "orders_total_cents_check" CHECK (total_cents >= 0 AND total_cents <= 99999999999999), CONSTRAINT "orders_status_check" CHECK (status IN ('pending', 'paid', 'shipped', 'cancelled')), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL, "order_id" bigint NOT NULL, "product_id" bigint NOT NULL, "quantity" integer NOT NULL, "unit_price_cents" bigint NOT NULL, CONSTRAINT "order_items_order_id_product_id_key" UNIQUE ("order_id", "product_id"), CONSTRAINT "order_items_unit_price_cents_check" CHECK (unit_price_cents >= 0 AND unit_price_cents <= 999999999999), CONSTRAINT "order_items_quantity_check" CHECK (quantity > 0), CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "order_items_product_id_idx" ON "order_items" ("product_id") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL, "seller_id" bigint NOT NULL, "name" text NOT NULL, "price_cents" bigint NOT NULL, "stock" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "products_stock_check" CHECK (stock >= 0), CONSTRAINT "products_price_cents_check" CHECK (price_cents >= 0 AND price_cents <= 999999999999), CONSTRAINT "products_name_check" CHECK (length(btrim(name)) > 0), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "products_seller_id_idx" ON "products" ("seller_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL, "email" text NOT NULL, "display_name" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "users_display_name_check" CHECK (length(btrim(display_name)) > 0), CONSTRAINT "users_email_check" CHECK (email = btrim(email) AND position('@' IN email) > 1), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "products_seller_id_fkey" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_lower_email_key" ON "users" (lower(email))`);
        await queryRunner.query(`CREATE INDEX "products_lower_name_idx" ON "products" (lower(name))`);
        await queryRunner.query(`CREATE INDEX "orders_user_created_idx" ON "orders" (user_id, created_at DESC) INCLUDE (id, total_cents)`);
        await queryRunner.query(`CREATE INDEX "orders_pending_created_idx" ON "orders" (created_at DESC) INCLUDE (id, user_id, total_cents) WHERE status = 'pending'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "orders_pending_created_idx"`);
        await queryRunner.query(`DROP INDEX "orders_user_created_idx"`);
        await queryRunner.query(`DROP INDEX "products_lower_name_idx"`);
        await queryRunner.query(`DROP INDEX "users_lower_email_key"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "products_seller_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_product_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_order_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_user_id_fkey"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."products_seller_id_idx"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."order_items_product_id_idx"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "orders"`);
    }

}
